### ISSUE TITLE
Thoughts on Nuget

### ISSUE THREAD

**Issue by tomfulton** [leekelleher/umbraco-package-boilerplate#1]
Curious if you have any thoughts on using Nuget for the MSBuild task DLLs to avoid having to include them in the repo?  Looks like all 3 dependencies are available:

http://nuget.org/packages/MSBuildTasks/
http://nuget.org/packages/MSBuild.Umbraco.Tasks/
http://nuget.org/packages/SharpZipLib/

**Comment by leekelleher** [comment]
Great suggestion! :+1: 

I did start taking a look at pulling them in, but started to hit some snags.

The main one was SharpZipLib - on NuGet it's at v0.86.0 - but MSBuild.Umbraco.Tasks compiles against v0.84.0 specifically so throws an exception. Since v0.84.0 isn't available on NuGet, we can speak with Matt about updating MSBuild.Umbraco.Tasks.

Also there was an issue with the location of the directory the package is downloaded to, as in they might not be in the `/tools/` directory. But I'm sure that is configurable.  I'll take another look.

**Comment by leekelleher** [comment]
The more I think about this, the more I'm not sure how it should work.

Are we talking about including NuGet package references in the boilerplate or bootstrapper?

If it's the boilerplate, then the only point for the "package restore" feature would be the `Our.Umbraco.Package.csproj`. But then the assemblies would be copied across to the `/bin` directory.

How could we get those into the `/tools/` directory (at root-level)? (so that the `package.proj` MSBuild script can reference them)

I'm sure there's a solution; needs more thought.

**Comment by leekelleher** [comment]
Trying to come up with ideas on how to get the Tasks assemblies into the `/tools` directory.

Take a look at this batch script: https://gist.github.com/leekelleher/5349732

... but where/when to run it? (or am I completely missing a trick here?)

**Comment by tomfulton** [comment]
Thinking on the boilerplate.  I think a nuget package can be "installed" but not referenced from a project so it doesn't end up in `/bin/` - the MSBuildTasks project seems to work like this.  It just adds the DLL/target files to `/.build/` without adding references to the project.  The restore doesn't do this as it's probably done by a .ps1 script, but I wonder if we can point the build script to read the DLLs directly from the `/packages/` folder, or if that's even kosher?

Regarding the batch script, not sure where you'd be able to run that - maybe from `build.cmd`?  Is it required to get those DLLs into `/tools/`?

Just thinking out loud here, maybe this adds too much complexity?

**Comment by leekelleher** [comment]
I check the MSBuild.Umbraco and SharpZipLib, if you reference them from a `.csproj` then they'll copy/reference them in the project's `/bin/` directory. (Which is no good for the 'boilerplate'.)

The problem (I found) with trying to reference the DLLs directly from the `/packages/` directory is knowing the path - as NuGet will include the package version in the folder name (e.g. `/packages/MSBuildTasks.1.4.0.56/...`) we'd need to keep track of the version numbers too. :-$

As for the batch script - yes, it could be ran from the `build.cmd`, or as an `Exec` task in the MSBuild script (`package.proj`)?

Actually I'm starting to think that's a good solution - however it does mean that we'll need to bundle the `/.nuget` files with the boilerplate. :-P

**Comment by leekelleher** [comment]
Just raised an issue over on the MSBuild.Umbraco repo.
https://bitbucket.org/mattbrailsford/msbuild.umbraco/issue/1/compile-against-sharpziplib-v0860-nuget

**Comment by tomfulton** [comment]
Regarding the references, there's no reason we need to reference them in the project, so for now you could simply delete the references after installing.  The restore shouldn't add them back as references, this only happens during install I think.

Yeah, the version # is always an issue when we try to do these things.  Theoretically we could read the correct version # from `packages.config`, just a bit more work :)

I like the idea of the batch script running as part of the MSBuild script rather than the `build.cmd` if it's possible.

I think adding the `/.nuget` files is acceptable.  Most package devs will probably want that anyway (?).  I've started experimenting with using the UmbracoCms.Core package for my packages instead of the traditional `/lib/' approach, seems to be working well.

Will think more on this today...

**Comment by leekelleher** [comment]
Closing this issue. A lot has changed in the world of NuGet, any updates to the boilerplate would take latest practices into account.
